version: '3.3'

services:
  blogpost:
    build: 
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    environment:
      - DATABASE_URL=host=postgres user=postgres password=postgres dbname=blogpost sslmode=disable
      - REDIS_HOST=redis 
      - REDIS_PORT=6379
    restart: unless-stopped
    depends_on:
      - redis
      - postgres
    networks:
      - backend

  redis:
    image: redis:latest
    restart: always
    volumes:
      - redis_volume_data:/data
    ports:
      - 6380:6379
    healthcheck:
      test: ["CMD-SHELL", "redis-cli ping | grep PONG"]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - backend

  postgres:
    image: "postgres:latest"
    environment:  
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_DB=blogpost
    networks:
      - backend
    ports:
      - "5433:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5

networks:
  backend:

volumes:
  redis_volume_data: {}
  pgdata: {}
